# Generated by Django 4.2 on 2025-10-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal User'), ('courier', 'Courier'), ('warehouse', 'Warehouse Courier'), ('business', 'Business User')], default='normal', max_length=20),
        ),
    ]
