# Generated by Django 4.2 on 2025-10-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
