# Generated by Django 4.2 on 2026-01-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_route_route_type_routestop_postmat_and_more'),
        ('accounts', '0005_user_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='warehouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.warehouse'),
        ),
    ]
