# Generated by Django 4.2 on 2025-10-26 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postmat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postmats', to='logistics.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Stash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('is_empty', models.BooleanField(default=True)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('postmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stashes', to='postmats.postmat')),
            ],
        ),
    ]
