# Generated by Django 4.2 on 2025-11-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postmats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmat',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
    ]
