# Generated by Django 4.2 on 2025-12-02 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_actualization_options'),
        ('postmats', '0002_rename_warehouse_id_postmat_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='stash',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stash', to='packages.package'),
        ),
    ]
