# Generated by Django 4.2 on 2025-12-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_actualization_options'),
        ('postmats', '0003_stash_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmat',
            name='address',
            field=models.CharField(blank=True, help_text='Cached address from geocoding or seeder', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postmat',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stash',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stash_assignment', to='packages.package'),
        ),
    ]
