# Generated by Django 4.2 on 2026-01-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmats', '0005_zone_postmat_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postmats/'),
        ),
    ]
