# Generated by Django 4.2 on 2026-01-12 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postmats', '0006_postmat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmat',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Only for Pickup Points. The business user who owns this point.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmat',
            name='type',
            field=models.CharField(choices=[('locker', 'Locker'), ('pickup_point', 'Pickup Point')], default='locker', help_text='Locker has stashes. Pickup Point is for business users.', max_length=20),
        ),
    ]
