# Generated by Django 4.2 on 2025-10-26 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('postmats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_code', models.CharField(blank=True, max_length=10, null=True)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('weight', models.PositiveIntegerField()),
                ('unlock_code', models.CharField(blank=True, max_length=10, null=True)),
                ('route_path', models.JSONField()),
                ('destination_postmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_packages', to='postmats.postmat')),
                ('origin_postmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_packages', to='postmats.postmat')),
            ],
        ),
        migrations.CreateModel(
            name='Actualization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('placed_in_stash', 'Placed in Stash'), ('in_transit', 'In Transit'), ('in_warehouse', 'In Warehouse'), ('delivered', 'Delivered'), ('picked_up', 'Picked Up')], default='created', max_length=20)),
                ('route_remaining', models.JSONField(blank=True, null=True)),
                ('courier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actualizations', to=settings.AUTH_USER_MODEL)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizations', to='packages.package')),
                ('routes', models.ManyToManyField(blank=True, related_name='actualizations', to='logistics.route')),
                ('warehouse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actualizations', to='logistics.warehouse')),
            ],
        ),
    ]
