# Generated by Django 4.2 on 2025-11-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_actualization_created_at_alter_package_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualization',
            options={'ordering': ['-created_at']},
        ),
    ]
