# Generated by Django 4.2 on 2025-12-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_package_receiver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='receiver_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
