# Generated by Django 4.2 on 2026-01-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_package_receiver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
