# Generated by Django 4.2 on 2026-01-08 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_magazine'),
        ('postmats', '0006_postmat_image'),
        ('packages', '0007_alter_package_pickup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='source_magazine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='business.magazine'),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination_postmat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_packages', to='postmats.postmat'),
        ),
        migrations.AlterField(
            model_name='package',
            name='origin_postmat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_packages', to='postmats.postmat'),
        ),
    ]
