# Generated by Django 4.2 on 2025-10-26 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=60)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('connections', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('delayed', 'Delayed'), ('closed', 'Closed')], default='operational', max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destinations', to='logistics.warehouse')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_origins', to='logistics.warehouse')),
            ],
        ),
    ]
