# Generated by Django 4.2 on 2025-12-03 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_actualization_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='route',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='route',
            name='origin',
        ),
        migrations.AddField(
            model_name='route',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='courier',
            field=models.ForeignKey(default=123, limit_choices_to={'role': 'warehouse'}, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_routes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='estimated_duration',
            field=models.IntegerField(blank=True, help_text='Minutes', null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='total_distance',
            field=models.FloatField(default=123, help_text='Total route distance in km'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(help_text='Stop sequence (0 = first)')),
                ('distance_from_previous', models.FloatField(default=0, help_text='km from previous stop')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='logistics.route')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.warehouse')),
            ],
            options={
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'order')},
            },
        ),
        migrations.CreateModel(
            name='RoutePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dropoff_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoffs', to='logistics.routestop')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='packages.package')),
                ('pickup_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='logistics.routestop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_packages', to='logistics.route')),
            ],
            options={
                'unique_together': {('route', 'package')},
            },
        ),
    ]
