# Generated by Django 4.2 on 2025-12-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_route_options_remove_route_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, help_text='Cached address from geocoding', max_length=255, null=True),
        ),
    ]
