# Generated by Django 4.2 on 2025-12-24 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postmats', '0005_zone_postmat_zone'),
        ('logistics', '0003_warehouse_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('line_haul', 'Line Haul (Warehouse-to-Warehouse)'), ('last_mile', 'Last Mile (Local Delivery)')], default='line_haul', max_length=20),
        ),
        migrations.AddField(
            model_name='routestop',
            name='postmat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postmats.postmat'),
        ),
        migrations.AlterField(
            model_name='route',
            name='courier',
            field=models.ForeignKey(limit_choices_to={'role': 'warehouse'}, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.warehouse'),
        ),
    ]
