# Generated by Django 4.2 on 2026-01-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessuserrequest',
            old_name='full_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='businessuserrequest',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='businessuserrequest',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessuserrequest',
            name='tax_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
