# Generated by Django 4.2 on 2026-01-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_rename_full_address_businessuserrequest_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuserrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
